// Generated by CoffeeScript 1.6.3
/*
This module provides some convenience functions for working with
[Mori](https://github.com/swannodette/mori) data structures.
*/

var all, any, countAtLeast, isEmpty, iterateAndTrim, second, _;

_ = require('mori');

second = function(coll) {
  /* Returns the second element of the given collection.*/

  return _.nth(coll, 1);
};

countAtLeast = function(n, coll) {
  /* Tests if the collection `coll` has at least `n` elements.*/

  return _.count(_.take(n, coll)) >= n;
};

isEmpty = function(coll) {
  /* Tests if the given collection contains no elements.*/

  return !_.seq(coll);
};

any = function(p, coll) {
  /*
  Tests if predicate `p` is true for any element of the collection `coll`.
  */

  return _.seq(_.filter(p, coll)) != null;
};

all = function(p, coll) {
  /*
  Tests if predicate `p` is true for all elements of the collection `coll`.
  */

  return !any((function(x) {
    return !p(x);
  }), coll);
};

iterateAndTrim = function(f, x) {
  /*
  Returns a lazy sequence of `x`, `f(x)`, `f(f(x))` and so on, which is
  terminated at the first `null` or `undefined`.
  */

  return _.take_while((function(x) {
    return x != null;
  }), _.iterate(f, x));
};

module.exports = {
  second: second,
  countAtLeast: countAtLeast,
  isEmpty: isEmpty,
  any: any,
  all: all,
  iterateAndTrim: iterateAndTrim
};
